version: 2.1
orbs:
  architect: giantswarm/architect@2.1.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: e2esetup-certs-to-app-catalog
          app_catalog: "default-test-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "e2esetup-certs"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: e2esetup-vault-to-app-catalog
          app_catalog: "default-test-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "e2esetup-vault"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
