version: 2.1

orbs:
  architect: giantswarm/architect@0.7.0

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/go-architect-legacy:
          name: go-deploy
          command: deploy
          filters:
            branches:
              only: vault-k8s-auth
